version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/backend/springboot"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "uv"
    directory: "/backend/fastapi"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"