apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
  namespace: skala3-finalproj-class2-team9
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
