apiVersion: apps/v1
kind: Deployment
metadata:
  name: workmaite-ai-agent
  namespace: skala3-finalproj-class2-team9
  labels:
    app: workmaite-ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workmaite-ai-agent
  template:
    metadata:
      labels:
        app: workmaite-ai-agent
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: workmaite-ai-agent
          image: amdp-registry.skala-ai.com/skala26a-ai2/workmaite-ai-agent:cicd-pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: workmaite-ai-agent
  namespace: skala3-finalproj-class2-team9
  labels:
    app: workmaite-ai-agent
spec:
  type: ClusterIP
  selector:
    app: workmaite-ai-agent
  ports:
    - name: http
      port: 8000
      targetPort: 8000
