apiVersion: apps/v1
kind: Deployment
metadata:
  name: workmaite-backend
  namespace: skala3-finalproj-class2-team9
  labels:
    app: workmaite-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workmaite-backend
  template:
    metadata:
      labels:
        app: workmaite-backend
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: workmaite-backend
          image: amdp-registry.skala-ai.com/skala26a-ai2/workmaite-backend:252e23c
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-1-postgresql.postgres.svc.cluster.local:5432/sk-team-9"
            - name: SPRING_DATASOURCE_USERNAME
              value: "team9"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "team9postgres1234"
            - name: AI_URL
              value: "http://workmaite-ai-agent:8000"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-1-master.redis.svc.cluster.local"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              value: "Skala25a!23$"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: workmaite-backend
  namespace: skala3-finalproj-class2-team9
  labels:
    app: workmaite-backend
spec:
  type: ClusterIP
  selector:
    app: workmaite-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080