apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workmaite-team9
  namespace: skala-argocd  # ArgoCD가 설치된 네임스페이스 (교육환경 제공)
spec:
  project: default
  source:
    repoURL: https://github.com/als7928/Workmaite.git
    targetRevision: main  # 배포 대상 브랜치
    path: k8s  # 이 폴더 안의 yaml들을 EKS에 배포
  destination:
    server: https://kubernetes.default.svc  # 현재 클러스터 내부 API 서버
    namespace: skala3-finalproj-class2-team9
  syncPolicy:
    automated:
      prune: false   # k8s yaml 삭제해도 실제 Pod는 자동 삭제 안 함 (개발 중 안전하게 false)
      selfHeal: true # kubectl로 직접 수정 시 ArgoCD가 Git 상태로 되돌림
    syncOptions:
      - CreateNamespace=false  # 네임스페이스 자동 생성 안 함 (교육환경에서 이미 제공)